services:
  db:
    image: postgres:15
    container_name: fluid-tasks-db
    environment:
      POSTGRES_DB: fluid_tasks
      POSTGRES_USER: tinsiz
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: fluid-tasks-app
    ports:
      - "${APP_PORT:-8081}:${SERVER_PORT:-8080}"
    depends_on:
      - db
    environment:
      SERVER_ADDRESS: 0.0.0.0
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/fluid_tasks
      SPRING_DATASOURCE_USERNAME: tinsiz
      SPRING_DATASOURCE_PASSWORD: password
